# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  docker: circleci/docker@1.5.0
  gradle: circleci/gradle@2.2.0
# Orchestrate or schedule a set of jobs
jobs:
  build-and-push-java:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/gift_advisor_v2/spring_app
      - docker/push:
          digest-path: /tmp/digest_spring.txt
          image: $CIRCLE_PROJECT_USERNAME/gift_advisor_v2/spring_app
      - run:
          command: |
            echo "Digest is: $(</tmp/digest_spring.txt)"

  build-and-push-angular:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/gift_advisor_v2/frontend_app
          docker-context: gift-advisor/
      - docker/push:
          digest-path: /tmp/digest_angular.txt
          image: $CIRCLE_PROJECT_USERNAME/gift_advisor_v2/frontend_app
      - run:
          command: |
            echo "Digest is: $(</tmp/digest_angular.txt)"

  build-and-push-bd:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/gift_advisor_v2/postgres_app
      - docker/push:
          digest-path: /tmp/digest_bd.txt
          image: $CIRCLE_PROJECT_USERNAME/gift_advisor_v2/postgres_app
      - run:
          command: |
            echo "Digest is: $(</tmp/digest_bd.txt)"


workflows:
  build-docker-image:
    jobs:
      - gradle/test:
          test_results_path: build/reports
          executor:
            name: gradle/default
            tag: '11.0'
      - gradle/run:
          executor:
            name: gradle/default
            tag: '11.0'
      - build-and-push-java:
          requires: 
            - gradle/run
      - build-and-push-angular:
          requires: 
            - gradle/run
      - build-and-push-bd:
          requires: 
            - gradle/run
